### ISSUE TITLE
Support for RegEx paths

### ISSUE THREAD

**Issue by Aurelsicoko** [steambap/koa-tree-router#1]
Do you plan to support path string such as `/user/:id`? Using this library for example https://github.com/pillarjs/path-to-regexp

**Comment by steambap** [comment]
Yes. I've updated readme.md to let everyone know how to write routes.

There are 3 types of routes:

1.Static
```
Pattern: /static

 /static                   match
 /anything-else            no match
```

2.Named

Named parameters have the form `:name` and only match a single path segment:
```
Pattern: /user/:user

 /user/gordon              match
 /user/you                 match
 /user/gordon/profile      no match
 /user/                    no match
```

3.Catch-all

Catch-all parameters have the form `*name` and match everything. They must always be at the **end** of the pattern:

```
Pattern: /src/*filepath

 /src/                     match
 /src/somefile.go          match
 /src/subdir/somefile.go   match
```

This library use a tree data structure to represent routes. And that is the reason this library is much faster than koa-router, which is based on `path-to-regexp`. Therefore I won't use `path-to-regexp`.

**Comment by Aurelsicoko** [comment]
Awesome! Thanks for the quick answer. I have another question, how the library deals with multiple middlewares per route?

```js
const middleware = (ctx, next) => {
  // Do stuff...
};

const action = (ctx, next) => {
  ctx.send('ok');
};

router.get("/", [middleware, action]);
```

Is this possible?

**Comment by steambap** [comment]
Yes.

If you are using vscode or webstorm(anything that support ts definition), you will see that you can use an array of middleware.

![ts](https://user-images.githubusercontent.com/9855651/34634871-5f8c78d8-f2c3-11e7-9ce3-b4ff27b078ad.png)

**Comment by Aurelsicoko** [comment]
Thank you @steambap! I will take a deep look to ensure your library could be integrated into [Strapi](https://github.com/strapi/strapi).
