### ISSUE TITLE
Types are not using Koa parametrized context

### ISSUE THREAD

**Issue by IlyaSemenov** [steambap/koa-tree-router#13]
Koa is now using parametrized contexts:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b081a5b/types/koa/index.d.ts#L689-L705

koa-tree-router loses those typings (its Router class is not parametrized at all).

For example, that's how koa-router handles types:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1645790/types/koa-router/index.d.ts#L162

The point is being able to provide `State` interface and then have typings for `ctx.state` in the middleware:

```ts
import Router from "koa-router"

export interface State {
	foo: string
}

const router = new Router<State>()

router.get("/ping", async ctx => {
	// Here Typescript knows that ctx.state.foo is a string
})
```

(As you may know, [koa-router has been sold](https://news.ycombinator.com/item?id=19156707), so I'm looking for an alternative—just in case.)

**Comment by steambap** [comment]
Thank you for bring it up! I have published a new version (0.4.7) to support the parameterized context.
