### ISSUE TITLE
Why is this module more performant than find-my-way?

### ISSUE THREAD

**Issue by wenq1** [steambap/koa-tree-router#17]
From the benchmark this module is even faster than find-my-way. Both use radix tree implementation. I wonder why is this module faster?

**Comment by steambap** [comment]
`find-my-way` is trying to be framework independent, including many features like uri decode, query string, and regex support, etc. But as far as I know it is only used by the author's own framework `fastify`.
If it removes those features, and let the HTTP framework handle them, then I think both module will be the about the same.

**Comment by wenq1** [comment]
Thanks
