### ISSUE TITLE
Swagger for koa tree router

### ISSUE THREAD

**Issue by RakanAljamal** [steambap/koa-tree-router#23]
Is there a possible way to auto-generate swagger using koa tree router, 

[Swagger-koa](https://www.npmjs.com/package/swagger-koa) uses the default routing mechanism that comes from Koa itself. 
In my case we're using koa tree router and the swagger keeps failing to generate modules / routes. 

Any idea how to fix it , 
Thanks

**Comment by steambap** [comment]
What is error?

Also, I take a quick look at swagger-koa code. There is only one GET koa-route and I see no need to switch.
