### ISSUE TITLE
Support auto-generated OPTIONS handler / Distinguish between 501 and 405 errors

### ISSUE THREAD

**Issue by lehni** [steambap/koa-tree-router#5]
First of all, thank you for creating this router! After looking at `koa-router`'s code, I realized that performance should be much better if it was backed by a tree structure and went looking further, and found this!

One feature that `koa-router` offers that appears to be missing here, but would probably be really easy to implement is the `allowedMethods()` middleware.

From a quick glance at the following lines it looks like the functionality is mostly there, it would just need to be exposed through a handler:

https://github.com/steambap/koa-tree-router/blob/93784f0e47b3b4f874fa6efc854339a3b2dcdca7/router.js#L79-L91

Also, it looks like currently when a method is not found, the router always sends a 405 error back (but only if a `onMethodNotAllowed()` handler is defined, why not always send a default one?), without distinguishing 405 and 501, as `koa-router` does:

https://github.com/alexmingoia/koa-router/blob/590df78ef38a557e9ce86a14bd9bfe567c5701a1/lib/router.js#L419-L450

Some more information:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/501

https://github.com/alexmingoia/koa-router/issues/7

Would you accept a PR for this? Do you have any opinions on how it should be controlled through options?

**Comment by steambap** [comment]
First of all, I would definitely accept a PR for distinguish between 501 and 405 errors.

There are 2 reasons that I do not set a default handler:
1. I only want to have 405 in my dev environment, not in production. In that way, I can get some hint on what is available in dev environment while not expose those informations in production.
2. I usually have a "catch all" handler somewhere in my actual app. In such case, passing a callback to router level seems less flexible.

**Comment by lehni** [comment]
@steambap unfortunately I've now decided to use a different approach for routing that is not based on `koa-tree-router`. The main problem was that it wasn't tolerating such routes to coexist:

```js
'/users/current'
'/users/:id'
```

etc.

**Comment by steambap** [comment]
I know there are Golang tree-based router that support those routes. However, if I'm using a tree-based, I want the best performance. That's why my implementation is based on httprouter, which does not support such routes.
